name: Deploy frontend to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Clean Install
          uses: qcastel/github-actions-maven/actions/maven@master
          with:
            maven-args: "clean install"
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cuber-app" #Must be unique in Heroku
          heroku_email: "joosep.parts@gmail.com"
          appdir: "backend" # <- This will point to the api folder in your project
